### ISSUE TITLE
EventID mapping fails to match "failed to log in from" event

### ISSUE THREAD

**Issue by ralphdt** [Xboarder56/SYNOLOGY-DSM--DSM#1]
The regex in DSM Editor fails to match the EventID mapping for "failed to login from" events off a DS-3615XS

![screen shot 2019-02-11 at 21 58 31](https://user-images.githubusercontent.com/15196927/52596432-34cec580-2e48-11e9-8d5d-38f2c15caa01.png)
![screen shot 2019-02-11 at 21 59 02](https://user-images.githubusercontent.com/15196927/52596465-44e6a500-2e48-11e9-92e8-6fe6ffb5483b.png)

**Comment by ralphdt** [comment]
My regex is shockingly bad, can only suggest
System\s\w+:
should be
SYSTEM:

**Comment by ralphdt** [comment]
<12>Feb 11 22:18:07 xxxx-nas-1 Connection SYSTEM:	User [admin] from [192.168.1.130] failed to log in via [DSM] due to authorization failure.

**Comment by Xboarder56** [comment]
@ralphdt 

Give this regex a shot! It should fix the issue from my quick testing. Thanks for opening an issue! Once I get back to my laptop I will upload the change to the main tree if you notice it is all good!

Connection (?:SYSTEM|):\s(\w+)\s\[\w+\]\s\w+\s\[\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\]\s(failed\s\w+\s\w+\s\w+|logged\s\w+\s\w+)

**Comment by ralphdt** [comment]
** BEWARE - It may be me, but the \[ and \] removes the backslash \ when doing a cut & paste which will cause the regex to fail when copied **

Connection ?:SYSTEM|:\s(\w+)\s\[\w+\]\s\w+\s\[\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}\]\s(failed\s\w+\s\w+\s\w+|logged\s\w+\s\w+\s\w+)

I tested the above https://www.regexpal.com/ and made the change to DSM editor and EventID matches $1 + $2 = "User failed to log in". I just need to get it to change from "unknown log event" in the Log Activity now.

**Comment by ralphdt** [comment]
I needed to use hostname instead of SrcIP in the LogSource configuration and a "User Failed to Login" (User Login Failure) now matches LogSource SynoSysLog. Hope the regex gets rolled back into mainline ok.

**Comment by ralphdt** [comment]
** BEWARE - the \[ and \] need to be added
It may be DSM 6.2 DS-3615XS specific, but I get 2 different logs for failed login. Not sure of any pattern.

So I needed to add a 4th regex 
Connection ?:SYSTEM|:\s(\w+)\s\[\w+\]\s(failed\s\w+\s\w+\s\w+|logged\s\w+\s\w+\s\w+)\sfrom\s\[\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}\]

Once this was added and the Multiple Failed Auth rule lowered from 10 to 5, then I could get an "Offense" generated and had logs ready to replay using logrun.pl

**Comment by Xboarder56** [comment]
Sounds good. Yeah I’m basing this all off the 918 DSM 6.2 update 4. I did notice in your screenshot your authentication method seems to be grabbing the entire field. I would look to change that to group 1 to resolve that. 

Hopefully tomorrow I’ll get some time to update the main tree with the changes. Let me know if you notice anything else weird. 

The new regex has been uploaded to the repo.
