### ISSUE TITLE
Information & Warning syslog sent from Synology - "failed to log in"

### ISSUE THREAD

**Issue by ralphdt** [Xboarder56/SYNOLOGY-DSM--DSM#2]
EXAMPLE SYSLOG FOR A FAILED LOGIN
Connection: SYSTEM:	Last message 'SYSTEM:	User [marc]' repeated 4 times, suppressed by syslog-ng on 95.163.121.204
Connection SYSTEM:	User [marc] from [195.80.227.73] failed to log in via [DSM] due to authorization failure.
Connection SYSTEM:	User [marc] failed to log in from [195.80.227.73] via [DSM].
Connection SYSTEM:	User [marc] failed to log in from [195.80.227.73] via [DSM].
Connection SYSTEM:	User [marc] from [195.80.227.73] failed to log in via [DSM] due to authorization failure.
Connection SYSTEM: User [marc] from [195.80.227.73] failed to log in via [DSM] due to authorization failure.
Connection SYSTEM: User [john] from [130.10.0.1] failed to log in via [DSM] due to authorization failure.
Connection SYSTEM: User [john] failed to log in from [130.10.0.1] via [DSM].
Connection SYSTEM: User [john] failed to log in from [130.10.0.1] via [DSM].
Connection SYSTEM: User [john] from [130.10.0.1] failed to log in via [DSM] due to authorization failure.
Connection SYSTEM: User [john] from [130.10.0.1] failed to log in via [DSM] due to authorization failure.

Above syslog (minus timestamp/host) for a "failed to log in" event. I get an "info" and "warning" message sent from my DS3615XS DSM 6.1.
Parsing both messages for the same failed login would increment the rule counter twice as quickly and create a false positive (the default QR rule is 10 times in 5 mins).

The regex included in regex_overrides.txt only parses the "warning" message, not the "info" message.

Synology Log Centre can be configured to send Info, Warn, Error & 9 different categories (including System, Connection, File Transfer)

Copy the above into a /tmp/ file and run the QR replay utility to create the offense "multiple failed logins from same user"

/opt/qradar/bin/logrun.pl -f ./qr-syn-logs.txt -u 95.163.121.204 -d 192.168.1.198 -p 514 1

The above is an FYI so I've created and closed this as an issue.

**Comment by Xboarder56** [comment]
I see what you mean however, I'm not getting any informational events when login failures occur on my side. Only warnings. I attached a photo for you to view with the output from the Synology Log Center view. I could look at adjusting the regex to look for [DSM]. vs [DSM} due to authorization failure.

![screen shot 2019-02-15 at 3 02 21 pm](https://user-images.githubusercontent.com/967563/52889041-18c27100-3133-11e9-9bf7-9e5b758147cb.png)

**Comment by ralphdt** [comment]
![image](https://user-images.githubusercontent.com/15196927/52914756-1e9b8c00-32c4-11e9-8d2c-8cd4d7e56570.png)


![image](https://user-images.githubusercontent.com/15196927/52914727-ca90a780-32c3-11e9-9fdd-a275df6a0e15.png)

Odd. as you say. I get Info & Warning. Just noticed I'm DSM 6.1.7-15284 Update 3 on DS3615XS
